### ISSUE TITLE
Support for git-lfs and multipart upload

### ISSUE THREAD

**Issue by strict-type** [roman-kiselenko/smolgit#4]
Hi @roman-kiselenko 

I am starting my journey from DevOps to programming and thought of learning `git` internal and started looking into the project. `smolgit` is something I found accidentally and surprised it was so simple compared to others. I am new to Go and would experiment with this project.

Question:
1. Can I self host this on EC2? Is there any simple docker method guide available?
2. How to add store to S3 to store repos?

Feature Request:
- [ ] Support `git-lfs`
- [ ] Support multipart transfer upload/download
- [ ] Support all the file to store in S3 including `git` and `git-lfs` with POSIX file system like JuiceFS to save the cost of storing the repos without loosing on the speed or performance.

Sorry for asking noob questions.
Thank you in anticipation!

**Comment by roman-kiselenko** [comment]
@prishacoder hello and thank you for your attention. 

- Can I self host this on EC2? Is there any simple docker method guide available?

I've added an instruction how to use it with docker, [please check it](https://github.com/roman-kiselenko/smolgit?tab=readme-ov-file#docker). 
If you don't use docker you can just download target platform from releases page and run it in vanilla linux.

- How to add store to S3 to store repos?

You can use https://github.com/awslabs/mountpoint-s3/ in order to create a directory for `smolgit` and set that directory in the `config.yaml` > `git.path`. 

I don't plan to support `git-lfs`, but I'm open to your suggestions and contributions to the code. 🙏

**Comment by strict-type** [comment]
@roman-kiselenko Thank you for response and adding the guide for docker deployment method & S3 mounting!

On the `git-lfs`, I checked `go-git` and found it doesn't support `git-lfs` as it requires `git-scm` binary and `go-git` is written in pure Go and doesn't require `git-scm` binary.

In this case, if we would like to add support for LFS in `smolgit` then we've to look for alternative solutions like [DVC](https://dvc.org) as `smolgit` uses `go-git` for git related modules. I think LFS support will be very helpful as ecosystem is moving towards ML and people have to interact with lots of big size data. I am currently reading DVC and the other ecosystem to manage LFS including `multi-part upload/download` as it requires to manage ML and large data files.

I am new to Go and just started learning, I will try to create PR in case I setup it successfully in my local. Will love to get your input on LFS support, if possible.

Thanks a lot again! 🙏

**Comment by strict-type** [comment]
I checked DVC and looks like the setup runs in parallel and supports multipart upload. So, we don't really need to integrate for the self use.
